name: Testing Integration

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
    paths:
      - '**.php'
      - '!docs/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0', '7.4' ]
        wordpress: [ '6.1', '6.0', '5.9', '5.8', '5.7', '5.6' ]
        include:
          - php: '8.1'
            wordpress: '6.1'
            coverage: 1
          - php: '8.1'
            wordpress: '5.9'
          - php: '7.3'
            wordpress: '5.9'
          - php: '7.3'
            wordpress: '5.8'
          - php: '7.3'
            wordpress: '5.7'
          - php: '7.3'
            wordpress: '5.6'
      fail-fast: false
    name: WordPress ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, zip, unzip

      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install

      - name: Build "testing" Docker Image
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: composer build-test

      - name: Run Tests w/ Docker.
        env:
          COVERAGE: ${{ matrix.coverage }}
          USING_XDEBUG: ${{ matrix.coverage }}
          DEBUG: ${{ matrix.debug }}
          SKIP_TESTS_CLEANUP: ${{ matrix.coverage }}
        run: composer run-test

      - name: Push Codecoverage to Coveralls.io
        if: ${{ matrix.coverage == 1 }}
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: vendor/bin/php-coveralls -v
